name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ":99"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version: 18
          cache: 'yarn'
      - name: Cache yarn
        id: cache-yarn
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-lock-${{ hashFiles('yarn.lock') }}
      - run: yarn install
      - name: Setup FireFox
        env:
          FIREFOX_URL: https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US
        run: |
          ACTUAL_URL=$(curl -Ls -o /dev/null -w %{url_effective} $FIREFOX_URL)
          curl --silent --show-error --location --fail --retry 3 --output /tmp/firefox.tar.bz2 $ACTUAL_URL
          sudo tar -xvjf /tmp/firefox.tar.bz2 -C /opt
          sudo ln -s /opt/firefox/firefox /usr/local/bin/firefox
          sudo apt-get install -y libgtk3.0-cil-dev libasound2 libasound2 libdbus-glib-1-2 libdbus-1-3
          rm -rf /tmp/firefox.*
          firefox --version
      - name: Setup geckodriver
        run: |
          export GECKODRIVER_LATEST_RELEASE_URL=$(curl https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r ".assets[] | select(.name | test(\"linux64.tar.gz$\")) | .browser_download_url")
          curl --silent --show-error --location --fail --retry 3 --output /tmp/geckodriver_linux64.tar.gz "$GECKODRIVER_LATEST_RELEASE_URL"
          cd /tmp
          tar xf geckodriver_linux64.tar.gz
          rm -rf geckodriver_linux64.tar.gz 
          sudo mv geckodriver /usr/local/bin/geckodriver
          sudo chmod +x /usr/local/bin/geckodriver
          geckodriver --version
      - name: Get Chrome
        run: |
          LAST_KNOWN_GOOD_VERSIONS_WITH_DL=$(curl -sL https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json)
          CHROME_LINK=$( echo "$LAST_KNOWN_GOOD_VERSIONS_WITH_DL" | jq '.channels.Stable.downloads.chrome[] | select(.platform=="linux64")| .url' )
          curl -sL -o  chrome-linux64.zip $CHROME_LINK
          CHROME_DRIVER_LINK=$( echo "$LAST_KNOWN_GOOD_VERSIONS_WITH_DL" | jq '.channels.Stable.downloads.chromedriver[] | select(.platform=="linux64")| .url' )
          curl -sL -o chrome-driver-linux64.zip $CHROME_DRIVER_LINK
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /usr/local/bin/chrome
          sudo chmod +x /usr/local/bin/chrome
          chrome --version
          unzip chrome-driver-linux64.zip
          sudo mv chrome-driver-linux64 /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      # - name: Setup Chrome
      #   run: |
      #     wget -O google-chrome-stable_current_amd64.deb -t 5 "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
      #     (sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install)
      #     rm -rf google-chrome-stable_current_amd64.deb
      #     sudo sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox --no-sandbox|g'         "/opt/google/chrome/google-chrome"
      #     google-chrome --version
      # - name: setup Chromedriver
      #   run: |
      #     CHROME_VERSION="$(google-chrome --version)"
      #     echo "CHROME_VERSION=${CHROME_VERSION}"
      #     export CHROMEDRIVER_RELEASE="$(echo $CHROME_VERSION | sed 's/^Google Chrome //')"
      #     echo "CHROMEDRIVER_RELEASE=${CHROMEDRIVER_RELEASE}"
      #     export CHROMEDRIVER_RELEASE=${CHROMEDRIVER_RELEASE%%.*}
      #     echo "CHROMEDRIVER_RELEASE=${CHROMEDRIVER_RELEASE}"
      #     curl --silent --show-error --location --fail --retry 4 --retry-delay 5 --output /tmp/chromedriver_linux64.zip
      #     "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${CHROMEDRIVER_RELEASE}"
      #     cd /tmp
      #     unzip chromedriver_linux64.zip
      #     rm -rf chromedriver_linux64.zip
      #     sudo mv chromedriver /usr/local/bin/chromedriver
      #     sudo chmod +x /usr/local/bin/chromedriver
      #     chromedriver --version
      - name: Setup Display
        run: |
          sudo apt-get install -y libxss1
          Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          exec "$@"
      - run: yarn test